name: result_types

description: A lightweight Dart package with Result and Failure types for explicit and composable error handling.
version: 0.0.2
repository: https://github.com/VARWA/result_types
homepage: https://github.com/VARWA/result_types
issue_tracker: https://github.com/VARWA/result_types/issues
topics:
  - result
  - error-handling
  - functional

environment:
  sdk: ">=3.7.2 <4.0.0"

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2


license: MIT
